# Generated by Django 4.2.7 on 2023-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=2083)),
                ('color', models.CharField(max_length=55)),
                ('brand_name', models.CharField(max_length=55)),
            ],
        ),
    ]
